import Head from "next/head";
import React from "react";
import { connect } from "react-redux";
import ArrivalCard from "../components/ArrivalCard";
import Footer from "../components/Footer";
import Header from "../components/Header";
import useAuth from "../hooks/useAuth";
import styles from "../styles/Home.module.css";

function Home({ setUser }) {
  const auth = useAuth();
  React.useEffect(() => {
    if (auth) {
      setUser(auth);
    }
  }, [auth]);

  const items = [
    {
      id: 1,
      name: "product 1",
      image: "/arrival1.png",
      price: 10,
    },
    {
      id: 2,
      name: "product 2",
      image: "/arrival2.png",
      price: 12,
    },
    {
      id: 3,
      name: "product 3",
      image: "/arrival3.png",
      price: 10,
    },
    {
      id: 4,
      name: "product 4",
      image: "/arrival4.png",
      price: 12,
    },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className={styles.container}>
        <div className={styles.hero}>
          <div className={styles.hero_mobile_image}>
            <img
              src="https://images.unsplash.com/photo-1501004318641-b39e6451bec6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1073&q=80"
              alt=""
            />
          </div>
          <div className={styles.hero_content}>
            <h1>
              Find Plant of Your{" "}
              <span className={styles.brand_text}>Interest</span>.
            </h1>
            <p className="text-sm mb-3 mt-3 text-gray-500">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis
              eleifend orci nunc, blandit massa, vitae. Quis in vitae est eu
              pulvinar sed. Netus lorem sit turpis tristique pharetra sit.
              Egestas felis feugiat augue auctor quam nisl vel sit sagittis.
            </p>

            <a href="#selector" className={styles.shop_selection_btn}>
              Shop Collection{" "}
              <span>
                <img src="/arrow-light.svg" alt="" />
              </span>
            </a>
          </div>
          <div className={styles.hero_image_desktop}>
            <img src="/hero_image_group.png" alt="" />
          </div>
        </div>
      </div>

      <div className={`${styles.listed__container}`}>
        <ul>
          <li>
            <img src="/brand1.png" alt="" />
          </li>
          <li>
            <img src="/brand2.png" alt="" />
          </li>
          <li>
            <img src="/brand3.png" alt="" />
          </li>
          <li>
            <img src="/brand4.png" alt="" />
          </li>
          <li>
            <img src="/brand5.png" alt="" />
          </li>
        </ul>
      </div>

      <div className={styles.container}>
        <div className={styles.journey__section}>
          <div className={styles.journey__image__desktop}>
            <img src="/journey.png" alt="" />
          </div>

          <div className={styles.journey__content}>
            <h2>Our Journey</h2>
            <p className="mt-5 mb-5 text-sm text-gray-500">
              Quis eleifend orci nunc, blandit massa, vitae. Dui nulla augue in
              id enim non. Venenatis aenean suscipit facilisis amet.
              Pellentesque nullam mi vitae neque ipsum. Quis in vitae est eu
              pulvinar sed. Netus lorem sit turpis tristique pharetra sit.
              Tortor ornare libero semper cursus. Mollis erat augue egestas
              laoreet est auctor.
            </p>
            <p className="mt-5 mb-5 text-sm text-gray-500">
              Dui nulla augue in id enim non. Venenatis aenean suscipit
              facilisis amet. Pellentesque nullam mi vitae neque ipsum. Sem
              magna ut pharetra vitae duis eu senectus sem risus. Morbi non,
              semper vestibulum euismod accumsan augue.
            </p>

            <a href="#more" className="hover:scale-105">
              Read More.
            </a>
          </div>
        </div>

        <div className={styles.fresh__arrival__section}>
          <div className={styles.section_header}>
            <h2>Fresh arrivals</h2>

            <div className={styles.arrivals__box}>
              {items.map((item, i) => {
                return (
                  <ArrivalCard
                    key={i}
                    image={item.image}
                    name={item.name}
                    price={item.price}
                  />
                );
              })}
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}

const mapDispatchToProps = (dispatch) => ({
  setUser: (user) =>
    dispatch({
      type: "SET_USER",
      user: user,
    }),
});
export default connect(null, mapDispatchToProps)(Home);
